syntax = "proto3";

package esp.v1;

service ESPService {
  // StreamControlRequest is called by the ESP client to offer streaming
  // capabilities to the server (Elasticsearch). The server will respond
  // with a stream of StreamControlResponses, each of which will indicate
  // to the client that it is ready to receive data for a specific stream.
  // The client will then make Stream calls for that stream until another
  // StreamControlResponse is received that indicates the stream should
  // be closed.
  rpc StreamControl(StreamControlRequest) returns (stream StreamControlResponse);

  // Stream is called by the ESP client to send data for a given stream.
  rpc Stream(StreamRequest) returns (StreamResponse);
}


message StreamControlRequest {
}

message StreamControlResponse {
  string stream_id = 1; // Unique identifier for the stream

  // TODO encode a way to indicate that the stream is closed
}

message StreamRequest {
  string stream_id = 1; // Unique identifier for the stream

  // TODO: data
}

message StreamResponse {
}

//message HelloResponse {
//  string reply = 1;
//}
