/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */
apply plugin: 'elasticsearch.build'
apply plugin: 'elasticsearch.internal-es-plugin'

esplugin {
  name 'x-pack-kafka-consumer'
  description 'The Kafka Consumer plugin adds a Kafka consumer, for consuming data directly from Kafka and indexing documents.'
  classname 'org.elasticsearch.xpack.kafkaconsumer.KafkaConsumerPlugin'
}

dependencies {
  implementation 'org.apache.kafka:kafka-clients:3.9.0'

  // nop all slf4j logging
  // workaround for https://github.com/elastic/elasticsearch/issues/93714
  runtimeOnly "org.slf4j:slf4j-nop:${versions.slf4j}"
  implementation("org.slf4j:slf4j-api:${versions.slf4j}")
}
