/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */
apply plugin: 'elasticsearch.internal-es-plugin'
//apply plugin: 'elasticsearch.internal-yaml-rest-test'
//apply plugin: 'elasticsearch.internal-cluster-test'

esplugin {
  name = 'x-pack-esp'
  description = 'The ESP plugin provides the Elasticsearch Stream Protocol.'
  classname = 'org.elasticsearch.xpack.esp.ESPPlugin'
}

dependencies {
  //compileOnly project(path: xpackModule('core'))
}
